import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import Footer from "@/components/Footer";
import HotelRegister from "@/components/HotelRegister";
import HeaderWrapper from "@/components/HeaderWrapper";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({


  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (

    <html lang="en">
      <body
      >
        <ClerkProvider>
          <HeaderWrapper />
          {false && <HotelRegister />}
          {children}
          <Footer />
        </ClerkProvider>
      </body>
    </html>
  );
}
