import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import Footer from "@/components/Footer";
import HeaderWrapper from "@/components/HeaderWrapper";
import { AppProvider } from '../context/AppContext.jsx'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({


  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (

    <html lang="en">
      <body>
        <ClerkProvider>
          <AppProvider>
            <HeaderWrapper />
            {children}
            <Footer />
          </AppProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
